-- create database

       create database Lola_Bookstore;
        use Lola_bookstore;

-- create tables
        create table customers (
           customer_id	  int primary key,
		   customer_name  varchar(20),
		   email          varchar(30),
		   city	          varchar(20),
		   signup_date    date

);
		create table orders (
          order_id	   int primary key,
          customer_id	   int references customers(customer_id), 
          book_id	       int references books(book_id),
          order_date	   date,
          quantity	   numeric,
          payment_method varchar(20),
          order_status   varchar(20)
);
		create table books(
            book_id	       int primary key,
            title 		    varchar(20),	
            author			varchar(20),
            genre			varchar(20),	
            price			numeric,	
            stock_quantity  numeric
);

-- data exploratin and cleaning
         select * from books;
         select * from orders;
         select* from customers;

-- check for nulls

         select * from orders where
         order_id is null or
          customer_id is null or
         book_id  is null or
         order_date is null or
         quantity is null or
         payment_method is null or
         order_status is null;
         select * from customers were
         customer_id is null or	
         customer_name is null or	
         email is null or	
         city is null or	
         signup_date is null;

-- check for duplicates
          with dupl as (
          select*,row_number()over(partition by customer_id,customer_name ) as rnk from customers
          )
          select * from dupl where rnk=2;
with dupli as (
          select*,row_number()over(partition by order_id ) as rnk from orders
          )
          select * from dupli where rnk=2;

-- checking for case sensitive duplicates
		
        select * from customers;
        select distinct city from customers;
        select *from books;
        select* from orders;
        select distinct payment_method from orders;
        select distinct order_status from orders;
        update orders
        set payment_method = lower(payment_method),
        order_status = lower(order_status);

-- orders before signup business check 
		select COUNT(*) total
        from orders o
        join customers c on o.customer_id = c.customer_id
		where o.order_date < c.signup_date;

-- analysis

-- Q1. How many total customers are in the database??
		select count(distinct customer_name) from customers;

-- Q2. How many books are available for sale?
		 select count(title) as num_of_books from books;
         
-- -- Q3. How many total orders were placed?
		select count(order_id) as total_orders from orders;
        
-- Q4.  What is the date range of orders in the dataset?
        select min(order_date) as first_orderdate,max(order_date) as last_orderdate from orders;
        
-- Q5.  What distinct genres are available?
		select count(distinct genre) from books;
        
-- Q6. What distinct order statuses exist?
		select distinct(order_status) from orders;
        
-- Q7. How many orders fall under each order status?
       select order_status,count(*) as total from orders
       group by order_status;
       
-- Q8. What payment methods are used and how often?
       select payment_method,count(*) as total from orders
       group by payment_method;
       
-- Q9. What is the total revenue generated by the bookstore?
		select sum(price * o.quantity) as total_revenue from books
        join orders o using(book_id);
        
-- Q10. What is the total revenue generated per book?
		select title,sum(price * o.quantity) as revenue from books
        join orders o using(book_id)
        group by title;
        
-- Q11. Which book has the highest quantity sold?
		select title,sum(o.quantity) as quantity_sold from books
        join orders o using(book_id)
        group by title
        order by quantity_sold desc
        limit 1;
        
-- Q12. Which genre generates the most revenue?
		select genre,sum(price*o.quantity) as revenue from books
        join orders o using (book_id)
        group by genre
        order by revenue
        limit 1;
        
-- Q13. What is the average order quantity?
        select avg(o.quantity) as avg_order_quantity from books
        join orders o using(book_id);
        
-- Q14. Which customers have placed more than one order?
        select customer_name, count(order_id) as total_orders from customers
        join orders using(customer_id)
        group by customer_name
        having total_orders >1;
        
-- Q15. Monthly order  trend
	select date_format(order_date,"%Y-%m") as Year_mnth,count(order_id) as orders from orders
        group by Year_mnth
        order by Year_mnth;
        
-- Q16. How does revenue vary by order status?
        select order_status,sum(price*o.quantity) as revenue from orders o
        join books using(book_id)
        group by order_status;
        
-- Q17. Which cities generate the highest total revenue?
        select city,sum(price*o.quantity) as revenue from customers
        join orders o using(customer_id)
        join books using(book_id)
        group by city
        order by revenue desc
        limit 1;
        
-- Q18. Who are the top 5 customers by total spending?
		select customer_name,sum(price*o.quantity) as total_spent from customers
        join orders o using(customer_id)
        join books using(book_id)
        group by customer_name
        order by total_spent desc
        limit 5;
        
-- Q19. What percentage of total revenue comes from completed orders?
        select 
        round(
				(sum(case when order_status = 'Completed' 
                  then quantity * price 
                  else 0 end)
                     /
						sum(quantity * price)) * 100, 2
							) as completed_order_revenue_pct
							from orders o
							join books b
							on o.book_id = b.book_id;
                            
-- Q20. Rank books by revenue within each genre.
		 with bookgen as (
                select genre,sum(price*o.quantity) as revenue from books
                join orders o using(book_id)
                group by genre)
                select*,rank()over (order by revenue desc) as rev_rnk from bookgen;

-- Q21. Compare revenue between 2024 and 2025.
				select year(order_date) as yr,sum(price*o.quantity) as revenue from books
                join orders o using(book_id)
                group by yr;
              
-- Q22. Are there any duplicate customer emails?
		select customer_id,count(email) as emails from customers
        group by customer_id
        having emails>1;
        
-- Q22. percentage of cancelled or returned orders
			select 
    round(
        (sum(case 
            when order_status in ('Cancelled', 'Returned') then 1 
            else 0 end) / COUNT(*)) * 100,2) as cancelled_or_returned_percentagefrom orders;

-- Q23. Identify customers who signed up but never placed an order.
            select customer_name from customers
            join orders using (customer_id)
            where signup_date is not null and order_id is null;


-- Q24.  Calculate running total revenue by month.
				select yr_mnth,revenue,sum(revenue) over(order by yr_mnth ) as running_total from
                (
                select date_format(order_date,"%Y-%m") as yr_mnth,sum(price*o.quantity) as revenue
                from books join orders o using(book_id)
                group by date_format(order_date,"%Y-%m")) t
                order by yr_mnth;
                
-- Q25. Segment customers into:Low value,Medium value,High value
			select customer_name,sum(price*o.quantity) as total_spent,case
            when sum(price*o.quantity)>750 then 'high value'
            when sum(price*o.quantity)> 500 then 'medium level'
            else 'low value' end spend_category from customers
        join orders o using(customer_id)
        join books using(book_id)
        group by customer_name
        order by total_spent desc;
            
-- Q26.Find customers who have ordered books from more than one genre.
		select customer_name,count(distinct genre) as orders from customers 
        join orders using(customer_id)
        join books using(book_id)
        group by customer_name
        having orders>1;

-- Q27. Identify books whose total sold quantity is above the average quantity sold per book.
             select title,sum(o.quantity) as total quantity from books 
             join orders o using (book_id)
             group by title
             having sum(o.quantity)>(select avg(quantity) from orders);

